# Generated by Django 4.2.4 on 2023-08-18 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CartMenu', models.CharField(max_length=50, verbose_name='CartMenu')),
                ('CartQty', models.IntegerField(verbose_name='CartQty')),
                ('CartPrice', models.IntegerField(verbose_name='CartPrice')),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='IngrdName')),
                ('qty_base', models.IntegerField(verbose_name='IngrdQtybase')),
                ('price', models.IntegerField(verbose_name='IngrdPrice')),
                ('origin', models.CharField(max_length=50, verbose_name='IngrdOrigin')),
                ('exprtdate_new', models.DateTimeField(default=datetime.datetime(2023, 8, 18, 16, 9, 53, 130725), verbose_name='ExprtDate_new')),
                ('term', models.IntegerField(default=10, verbose_name='Term')),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MenuName', models.CharField(max_length=50, verbose_name='MenuName')),
                ('MenuPrice', models.IntegerField(verbose_name='MenuPrice')),
                ('image', models.ImageField(default=None, upload_to='MacKiosk/static/images/')),
                ('category', models.CharField(choices=[('single', 'Single'), ('drink', 'Drink'), ('side', 'Side Menu'), ('set', 'Set Menu'), ('dessert', 'Dessert')], default='single', max_length=30, verbose_name='Category')),
            ],
            options={
                'db_table': 'menus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('OrderNum', models.IntegerField(verbose_name='OrderNum')),
                ('OrderQty', models.IntegerField(verbose_name='OrderQty')),
                ('OrderMenu', models.CharField(max_length=50, verbose_name='OrderMenu')),
                ('OrderDate', models.DateField(verbose_name='OrderDate')),
                ('OrderPrice', models.IntegerField(verbose_name='OrderPrice')),
                ('OrderComplete', models.BooleanField(default=False, verbose_name='CompleteStatus')),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_num', models.IntegerField(default=0, verbose_name='order_num')),
                ('content', models.CharField(max_length=50, verbose_name='Content')),
                ('sales', models.IntegerField(blank=True, default=0, verbose_name='Sales')),
                ('spend', models.IntegerField(blank=True, default=0, verbose_name='Spend')),
                ('salesdate', models.DateField(default=0, verbose_name='SalesDate')),
            ],
            options={
                'db_table': 'revenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CallCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.IntegerField(verbose_name='orderNum')),
            ],
        ),
    ]
