# Generated by Django 4.2.4 on 2023-08-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonaldapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='packing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('single', 'Single'), ('side', 'Side Menu'), ('set', 'Set Menu'), ('drink', 'Drink'), ('dessert', 'Dessert')], default='single', max_length=30),
        ),
    ]
