# Generated by Django 4.2.4 on 2023-08-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonaldapp', '0002_cart_packing_alter_menu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('packaging', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('drink', 'Drink'), ('set', 'Set Menu'), ('side', 'Side Menu'), ('dessert', 'Dessert'), ('single', 'Single')], default='single', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='menu',
            field=models.ManyToManyField(to='mcdonaldapp.menu'),
        ),
    ]
