# Generated by Django 3.1.2 on 2023-08-26 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonaldapp', '0002_auto_20230826_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mcdonaldapp.payment'),
        ),
    ]
