# Generated by Django 4.2.4 on 2023-08-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonaldapp', '0003_payment_delete_cart_alter_menu_category_payment_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='packaging',
            new_name='packging',
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('single', 'Single'), ('side', 'Side Menu'), ('set', 'Set Menu'), ('dessert', 'Dessert'), ('drink', 'Drink')], default='single', max_length=30),
        ),
    ]
