# Generated by Django 4.2.4 on 2023-08-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonaldapp', '0004_rename_packaging_payment_packging_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='packging',
            new_name='packing',
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('drink', 'Drink'), ('dessert', 'Dessert'), ('side', 'Side Menu'), ('set', 'Set Menu'), ('single', 'Single')], default='single', max_length=30),
        ),
    ]
