<<<<<<< HEAD
# Generated by Django 3.1.2 on 2023-08-25 15:05
=======
# Generated by Django 4.2.4 on 2023-08-25 04:48
>>>>>>> 4e9183112a65de2e4a08c700f952d1a8836f4326

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 4e9183112a65de2e4a08c700f952d1a8836f4326
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 4e9183112a65de2e4a08c700f952d1a8836f4326
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 4e9183112a65de2e4a08c700f952d1a8836f4326
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megacoffeeapp.menu')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megacoffeeapp.option')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('using_page', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 4e9183112a65de2e4a08c700f952d1a8836f4326
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('packaging', models.CharField(max_length=50)),
                ('orders', models.ManyToManyField(to='megacoffeeapp.Order')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('packaging', models.CharField(max_length=50)),
                ('orders', models.ManyToManyField(to='megacoffeeapp.order')),
>>>>>>> 4e9183112a65de2e4a08c700f952d1a8836f4326
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megacoffeeapp.quantity'),
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.CharField(max_length=50)),
                ('click_time', models.DateTimeField()),
                ('is_right', models.BooleanField()),
                ('page_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megacoffeeapp.page')),
            ],
        ),
    ]
