# Generated by Django 4.2.4 on 2023-08-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacoffeeapp', '0002_menu_option_order_quantity_payment_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='packaging',
            field=models.BooleanField(default=False),
        ),
    ]
