# Generated by Django 4.2.4 on 2023-08-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacoffeeapp', '0003_payment_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='packaging',
            field=models.CharField(max_length=50),
        ),
    ]
