# Generated by Django 3.1.2 on 2023-09-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacoffeeapp', '0003_alter_button_id_alter_menu_id_alter_option_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='button',
            old_name='page_number',
            new_name='page',
        ),
        migrations.RemoveField(
            model_name='page',
            name='start_time',
        ),
        migrations.AddField(
            model_name='page',
            name='brand',
            field=models.CharField(default='megacoffee', max_length=50),
        ),
        migrations.AlterField(
            model_name='button',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='option',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
