# Generated by Django 3.1.2 on 2023-09-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacoffeeapp', '0004_auto_20230920_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='menu', max_length=50),
        ),
    ]
