# Generated by Django 3.1.2 on 2023-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megacoffeeapp', '0005_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='using_page',
            field=models.IntegerField(null=True),
        ),
    ]
