# Generated by Django 4.2.4 on 2023-08-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='answer',
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='response',
            name='answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='introapp.answer'),
        ),
    ]
