# Generated by Django 4.2.4 on 2023-08-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0002_remove_answer_question_remove_response_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
