# Generated by Django 4.2.4 on 2023-09-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0003_alter_complete_id_alter_menu_id_alter_mission_mc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
